import React from "react";
import { db } from "../../db/client";
import { templates } from "../../db/schema";
import { desc } from "drizzle-orm";
import { FileText, Info, Layers } from "lucide-react";
import { Card } from "@/components/ui/card";
import { TemplateEditor } from "@/components/TemplateEditor";
import { NewTemplateForm } from "@/components/NewTemplateForm";

export const dynamic = "force-dynamic";

async function getTemplates() {
  try {
    return await db.select().from(templates).orderBy(desc(templates.id));
  } catch {
    return [];
  }
}

export default async function TemplatesPage() {
  const list = await getTemplates();
  const activeCount = list.filter((t) => t.isActive).length;

  return (
    <div className="space-y-5 max-w-7xl mx-auto">
      {/* Page header */}
      <Card className="p-4 sm:p-5 border-border">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <div className="flex items-center space-x-2">
              <FileText className="w-5 h-5 text-primary" />
              <h1 className="text-base sm:text-lg font-semibold text-text-main tracking-tight">
                Outreach Email Templates
              </h1>
            </div>
            <p className="text-xs text-text-secondary mt-0.5">
              Create and manage multiple cold email templates. Use{" "}
              <code className="font-mono text-brand-accent bg-brand-soft px-1 py-0.5 rounded text-[11px]">
                {"{{variable_name}}"}
              </code>{" "}
              syntax for dynamic channel and lead personalization.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <div className="px-3 py-1 rounded-lg bg-surface-200 border border-border text-xs flex items-center gap-2">
              <span className="text-text-muted">Total:</span>
              <span className="font-mono font-semibold text-text-main">{list.length}</span>
              <span className="text-border">|</span>
              <span className="text-text-muted">Active:</span>
              <span className="font-mono font-semibold text-emerald-400">{activeCount}</span>
            </div>
          </div>
        </div>
      </Card>

      {/* Variable reference card */}
      <Card className="p-4 border-border bg-surface-100">
        <div className="flex items-center gap-2 mb-2.5">
          <Info className="w-3.5 h-3.5 text-primary shrink-0" />
          <span className="text-[11px] font-semibold text-text-secondary uppercase tracking-wider">
            Available Merge Tags
          </span>
        </div>
        <div className="flex flex-wrap gap-2">
          {["{{first_name}}", "{{channel_name}}", "{{channel_url}}", "{{subscriber_count}}", "{{custom_line}}"].map((v) => (
            <code
              key={v}
              className="text-[11px] font-mono px-2 py-0.5 rounded bg-brand-soft border border-primary/20 text-brand-accent"
            >
              {v}
            </code>
          ))}
        </div>
        <p className="text-[11px] text-text-muted mt-2">
          <span className="font-medium text-text-secondary">custom_line</span> is AI-generated by Gemini — a hyper-personalized opening hook based on channel context.
        </p>
      </Card>

      {/* Add New Template Trigger & Form */}
      <NewTemplateForm />

      {/* Template list */}
      <div className="space-y-4">
        {list.length === 0 ? (
          <Card className="p-12 text-center text-xs text-text-muted space-y-2">
            <Layers className="w-8 h-8 text-text-muted mx-auto opacity-50" />
            <p className="font-medium text-text-secondary">No email templates found</p>
            <p>Click &quot;New Template&quot; above to create your first outreach sequence.</p>
          </Card>
        ) : (
          list.map((tmpl) => (
            <Card key={tmpl.id} className="p-4 sm:p-5">
              <TemplateEditor template={tmpl} />
            </Card>
          ))
        )}
      </div>
    </div>
  );
}