import React from "react";
import { db } from "../../db/client";
import { templates } from "../../db/schema";
import { desc } from "drizzle-orm";
import { FileText, Info } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { TemplateEditor } from "@/components/TemplateEditor";

export const dynamic = "force-dynamic";

async function getTemplates() {
  try {
    return await db.select().from(templates).orderBy(desc(templates.id));
  } catch {
    return [];
  }
}

export default async function TemplatesPage() {
  const list = await getTemplates();

  return (
    <div className="space-y-5 max-w-7xl mx-auto">
      {/* Page header */}
      <Card className="p-4 sm:p-5 border-border">
        <div className="flex items-center space-x-2">
          <FileText className="w-5 h-5 text-primary" />
          <h1 className="text-base sm:text-lg font-semibold text-text-main tracking-tight">
            Outreach Email Templates
          </h1>
        </div>
        <p className="text-xs text-text-secondary mt-0.5">
          Edit subject and body inline. Use{" "}
          <code className="font-mono text-brand-accent bg-brand-soft px-1 py-0.5 rounded text-[11px]">
            {"{{variable_name}}"}
          </code>{" "}
          syntax for dynamic content. Changes save instantly to the database.
        </p>
      </Card>

      {/* Variable reference card */}
      <Card className="p-4 border-border bg-surface-100">
        <div className="flex items-center gap-2 mb-2.5">
          <Info className="w-3.5 h-3.5 text-primary shrink-0" />
          <span className="text-[11px] font-semibold text-text-secondary uppercase tracking-wider">Available Variables</span>
        </div>
        <div className="flex flex-wrap gap-2">
          {["{{first_name}}", "{{channel_name}}", "{{channel_url}}", "{{subscriber_count}}", "{{custom_line}}"].map((v) => (
            <code
              key={v}
              className="text-[11px] font-mono px-2 py-0.5 rounded bg-brand-soft border border-primary/20 text-brand-accent"
            >
              {v}
            </code>
          ))}
        </div>
        <p className="text-[11px] text-text-muted mt-2">
          <span className="font-medium text-text-secondary">custom_line</span> is AI-generated by Gemini — a personalised opening hook based on the channel.
        </p>
      </Card>

      {/* Template list */}
      <div className="space-y-4">
        {list.length === 0 ? (
          <Card className="p-8 text-center text-xs text-text-muted">
            No templates configured. Run the database seed to install the default template.
          </Card>
        ) : (
          list.map((tmpl) => (
            <Card key={tmpl.id} className="p-4 sm:p-5">
              <div className="flex items-center gap-2 mb-1 justify-end">
                <Badge variant={tmpl.isActive ? "success" : "secondary"} className="font-mono text-[10px]">
                  {tmpl.isActive ? "Active" : "Inactive"}
                </Badge>
                <Badge variant="secondary" className="font-mono text-[10px]">
                  ID #{tmpl.id}
                </Badge>
              </div>
              <TemplateEditor template={tmpl} />
            </Card>
          ))
        )}
      </div>
    </div>
  );
}